### ISSUE TITLE
Is there any way too create a frameless window

### ISSUE THREAD

**Issue by zz5840** [GoogleChromeLabs/carlo#112]
As [frameless window](https://electronjs.org/docs/api/frameless-window#frameless-window) in electron

Or do you have any plan to develop this function

**Comment by pavelfeldman** [comment]
There is no way to do this today and no immediate plans to implement it.

**Comment by zz5840** [comment]
It's really a great pity, or I'll throw away the Electron

**Comment by zz5840** [comment]
It's really a great pity, or I'll throw away the Electron
