### ISSUE TITLE
Is there a way to cancel navigation intercepted by HttpRequest?

### ISSUE THREAD

**Issue by gadamsgh** [GoogleChromeLabs/carlo#129]
Is there a way to simply cancel a navigation? 

Example main.js:
```
const carlo = require('carlo');

(async () => {
    const app = await carlo.launch({args:['--auto-open-devtools-for-tabs']});
    app.on('exit', () => process.exit());
    app.serveFolder(__dirname);
    app.serveHandler(async function (request) {
        request.url() === 'http://www.github.com/' ? request.abort() : request.continue();
    });
    await app.load('https://www.google.com');
})();
```
In this example, we launch to www.google.com and then navigate to github.com from the console.
`window.location = 'http://www.github.com/'`

What I'd like to do in this case is leave the user where they were before attempting to navigate, without reloading.  Is this possible?
![image](https://user-images.githubusercontent.com/39625845/51713466-a0ff9b80-1ff7-11e9-8c3c-1426b60cdb28.png)

**Comment by pavelfeldman** [comment]
Fixed as https://github.com/GoogleChromeLabs/carlo/commit/17d972c6d43b0c2ede063b334c723f743dfbaa5c
