### ISSUE TITLE
New Release Please

### ISSUE THREAD

**Issue by bengl** [GoogleChromeLabs/carlo#142]
I'm currently depending on Carlo in a project (https://github.com/bengl/copher) using a github dependency, so that I can get some of the latest fixes (in particular, https://github.com/GoogleChromeLabs/carlo/commit/2fd4d918445c379a0d724aae732299e1dcdb7b91). I'd like to be able to depend on an npm release, to ensure proper semver adherence, etc.

Can we expect a new npm release with the latest fixes in the near future?

**Comment by pavelfeldman** [comment]
Published tip of the tree as `0.9.44`.
