### ISSUE TITLE
Any plan to support chrome.hid ?

### ISSUE THREAD

**Issue by gre** [GoogleChromeLabs/carlo#143]
https://developer.chrome.com/apps/hid was a great feature of Chrome apps.

**Comment by pavelfeldman** [comment]
The idea is that for the native features such as USB/HID, one would use Node.JS modules until the gap is closed in the web platform. Would that work for you?

**Comment by gre** [comment]
That makes sense. Unfortunately we're experimenting quite a few issues with `node-hid` implementation at Ledger, typically the fact you don't get a reliable `"disconnect"` event, but I guess it's the problem of the HID paradigm itself anyway.

Very eager to have WebUSB shipped and stabilized everywhere. Still a Draft spec at this point but 🤞
