### ISSUE TITLE
Is this unmaintained ?

### ISSUE THREAD

**Issue by sidevesh** [GoogleChromeLabs/carlo#163]
First of all, thanks for releasing this! Really has the potential for making it easier to build desktop applications without the full bloat of frameworks like electron.
I have used carlo in a number of projects and am really impressed.
That being said, there seems to be many critical issues open with no response.
Is carlo gonna be unmaintained ? and if not then what are the updates and fixes planned by the team ?

**Comment by esamattis** [comment]
I guess not https://news.ycombinator.com/item?id=22424885

**Comment by eligrey** [comment]
@paulirish Can we get an official deprecation notice?

**Comment by paulirish** [comment]
Hi all,

Apologies for the radio silence.

Unfortunately, **yes this repo is no longer maintained**. It was launched in @GoogleChromeLabs as we were uncertain about its long-term longevity, and unfortunately the original engineers working on the effort have left Google and we don't have the resources to sustain the project.

It's rather sad as many of us enjoy the functionality and design of Carlo. Perhaps it will live on in a community fork.

Paul
Chrome team

**Comment by frank-dspeed** [comment]
@paulirish i do adopt maintain and build open-pwa on it a little project from me to make a universal Plattform to run and install isolated apps on any device. We have for example already a concept that works like carlo but for android and ios via the webview of chrome. The Carlo code will extend that to Linux Windows MacOS

Thanks for the great idea. Of using Pupeeter for Window Control.



https://github.com/open-pwa/open-pwa

**Comment by sidevesh** [comment]
That concludes this issue then, closing,
I guess I should also add a deprecation notice to my project https://github.com/sidevesh/quark-carlo that used carlo
So Long, and Thanks for All the Fish

**Comment by visionarylab** [comment]
@frank-dspeed Contact with Microsoft and Mozilla. Since now only few teams left might willing to working with this if not from Google. 
Since Microsoft using Chrome now it make sense and co-align with their goal of WebView2. Probably after they finalized WebView2.

**Comment by frank-dspeed** [comment]
@visionarylab good idea my open-pwa project is like webview2 but it uses open interfaces to archive that there is no need for a extra spec while it is a nice extra integration thanks for the info i will add webview2 support to open-pwa

**Comment by crisdosaygo** [comment]
😢
