### ISSUE TITLE
Point carlo to an existing chrome instance?

### ISSUE THREAD

**Issue by oskbor** [GoogleChromeLabs/carlo#21]
Hi, could this scenario ever be supported? 
1. I open chrome and go to `localhost:3000`
2. A node process on `localhost`  serves some content to chrome and somehow does a handshake (prompts the user for approval?)
3. The running chrome instance can then be attached to as if `carlo` had launched it.

**Comment by trogper** [comment]
Probably won't work, since carlo launches chrome with additional command line flags.
Why do you need such thing?

**Comment by pavelfeldman** [comment]
Added an option to run Chrome from a known location in https://github.com/GoogleChromeLabs/carlo/commit/6062489933a9171f6a8daf9413335068a2f51aff. Running it against instance is problematic due to the startup flags.
