### ISSUE TITLE
link tag does not load (I can not load my CSS)

### ISSUE THREAD

**Issue by MAPESO** [GoogleChromeLabs/carlo#24]
The only way to give styles to our application is as follows:

```
<header>
      <style>
             body {
                  background: red;
              }
       </style>
</header>
```
for some strange reason I can not link my css styles through the link tag, It appears on the page but does not load. If someone could explain me why this behavior happens it would be incredible 🙏 
<img width="646" alt="screen shot 2018-11-01 at 23 47 08" src="https://user-images.githubusercontent.com/16585386/47895948-aef6b380-de30-11e8-9191-732ba597bdf9.png">

Have a nice day 😄 ❤️

**Comment by djyde** [comment]
try `href="styles.css"` if your `style.css` is in your `serveFolder` path.

**Comment by MAPESO** [comment]
@pavelfeldman  I just updated Carlo the problem disappeared 😸 🎉 
Thanks for the help @djyde  🙏

**Comment by MAPESO** [comment]
This issue does not make sense to exist, I'll close it 😺
