### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by dzek69** [GoogleChromeLabs/carlo#3]
Hi,

Can you tell something in README (or here) what was the motivation behind this project when we already have Electron and NW.js? How this differs from these platforms, how it helps to achieve something that's not possible/harder with these two?

Thank you

**Comment by samueldaviddelacruz** [comment]
[Carlo locates Google Chrome installed locally] this is already enough motivation for me.

**Comment by pavelfeldman** [comment]
As Samuel is saying, one of the motivations is to demonstrate how locally installed Chrome can be used with locally installed Node out of the box.

Unlike with Electron, Node v8 and Chrome v8 engines are decoupled in Carlo, providing a maintainable model with the ability of the independent updates of the underlying components. Carlo is less about branding and is more about productivity + giving the control over bundling to the user.

Happy to add this to the FAQ section.

**Comment by dzek69** [comment]
Thanks, sounds good to me :)

**Comment by feichao** [comment]
Sounds great~
