### ISSUE TITLE
window.open behavior

### ISSUE THREAD

**Issue by nessup** [GoogleChromeLabs/carlo#32]
How is window.open handled in the context of Carlo/Puppeteer? In Chrom(ium), a new tab would be created. But since Puppeteer/Carlo creates the window, it's unclear what UX would exist.

In the context of Carlo's use case, it seems the best thing to do would be to leave the behavior up to the Carlo developer via some sort of callback and override. For my use case, I'd like window.open calls to create another iframe, rather than a new window. Is this possible to do given Puppeteer's API support?

**Comment by pavelfeldman** [comment]
What is your use case? Caro assumes that the web content belongs to the actual app, so if won't do window.open on its own. Do you suggest enabling multi-window apps in Carlo?

**Comment by nessup** [comment]
Correction: assign a Frame to a window or an iframe

**Comment by nessup** [comment]
OK, for my specific use case with iframes, I may have found a solution. But in general, yes, I think Carlo should provide some interface for multiple windows. `App` would need to have multiple `page`s. Not sure what your thoughts are on how a PR about this should be formed given that there's a one-to-one relationship between an `App` and a `page` from Puppeteer.

**Comment by pavelfeldman** [comment]
Fixed, there are multiple windows now.

**Comment by nessup** [comment]
Hi Pavel, awesome!! Thank you so much.

It seems that calls to window.open from within an iframe doesn't trigger `targetcreated`. Instead, a new Chromium browser window is opened. Any ideas?
