### ISSUE TITLE
Why is this called Carlo?

### ISSUE THREAD

**Issue by GiacomoP** [GoogleChromeLabs/carlo#38]
The web is now full of projects and companies with Italian names, or random Italian words with no apparent meaning or connection to the technology used and service provided. They're also very hard to find through google.it, and I'd say that's really odd in our field.

This also causes excessive hilarity, but also unnecessary awkwardness, in an office environment, especially when Carlo here says that he's using this new fantastic tool called Carlo. Other people started saying "just carlo it up!" and Carlo doesn't really know how to take it sometimes. Is it something positive? Are they making fun of him while using this project as a cover?

Some people also refuse to "install carlo" in their computers, saying that's inhumane.

Can I suggest you rename the project to "Giancarlo Altrepicchi Della Valera born on the 18 of August 1987 in Rome", hoping it's unique enough?

Cheers

**Comment by vsemozhetbyt** [comment]
I may be wrong, but I suspect the name hint is:

https://en.wikipedia.org/wiki/Carlo_Collodi

with an association to Puppeteer counterpart?

**Comment by vsemozhetbyt** [comment]
Also: Mister Geppetto is ["Papa Carlo"](https://en.wikipedia.org/wiki/Buratino#Characters) in the Russian adaptation of Pinocchio.

**Comment by caffed** [comment]
As long as the the contrubuting guidlines dictate that only people named “Carlo” may be involved with the project 😛
