### ISSUE TITLE
examples/systeminfo on Windows 10 doesn't appear to work (no Window is opened)

### ISSUE THREAD

**Issue by frankhale** [GoogleChromeLabs/carlo#44]
On Windows 10 (2016 Surface Book) when I run the systeminfo example no window is opened and the example appears to be broken. I'm not sure where it's getting hung up, I tried a bit of debugging but since I am not very familiar with how Carlo works I was not able to get very far.

NOTE: The Terminal example works fine

**Comment by frankhale** [comment]
Thanks for the response, I removed that line but the example still doesn't open a window. The Terminal example seems to function fine though.

**Comment by pavelfeldman** [comment]
Another thing that Terminal does is detaches itself from the shell via restarting itself, in the very beginning of `main.js`. Maybe that helps?

```js
if (!process.env.CARLO) {
  child_process.spawn(process.argv[0], [__filename], {
     detached: true,
     env: { CARLO: 1, ...process.env }
  });
  process.exit(0);
  return;
}
```

**Comment by frankhale** [comment]
I tried that but still, no window. Not sure what is going on. The example in the README works fine which is like a stripped down version of the systeminfo example. I'll try on another machine soon.

**Comment by frankhale** [comment]
I'm going to close this as it works on my other Windows 10 computer. Weird! I'll try again later on my weird Windows Surface Book. One thing I have learned is that things behave very oddly on Windows Surface Books sometimes.

**Comment by salmanstar1** [comment]
Closed this issue about

**Comment by ab35** [comment]
It works fine on surface book 1 here.

**Comment by frankhale** [comment]
I deleted the repo, redownloaded and it worked fine. Not sure what was going on because I had already deleted several times and downloaded again. Anyway yes its working for me now.

**Comment by liudonghua123** [comment]
I have the same problem, and I added some logging and here is the snapshot of my code.

![image](https://user-images.githubusercontent.com/2276718/48758121-e9d66380-ecd9-11e8-9347-22875e7ca704.png)

**Comment by ab35** [comment]
@liudonghua123 I see that you commented out the `localDataDir` options but forgot to remove the comma in the line above.

That might cause the internal [`puppeteer.launch`](https://github.com/GoogleChrome/puppeteer/blob/86e09593bfc262a77798cbf9ab28754d242ba5ed/lib/Launcher.js#L77) function to silently fail, without throwing an error.

**Comment by ab35** [comment]
The failure is that on windows, pupeeter (c[arlo.js#498](https://github.com/GoogleChromeLabs/carlo/blob/ac0271a6ea21d4cefa51605e4bcba375053b7e8c/lib/carlo.js#L498)) is not able to create a local data directory in `__dirname` whose name begins with a dot:

```js
options.localDataDir = options.localDataDir || path.join(__dirname, '.local-data');
```

if one removes the dot, it works:
```js
options.localDataDir = options.localDataDir || path.join(__dirname, 'local-data');
```

However, it works fine when creating such directory outside of the main directory of the node process, like in the home directory:

```js
path.join(os.homedir(), '.carlosysteminfo'),
```

**Comment by ab35** [comment]
Kindly omit my previous messages (that I deleted) about the localDataDir. It is an error on my part: the default location is within `node_modules/carlo/lib` and it is created there at startup time when no option is provided by script. I do not really know what happens in your case @liudonghua123 .
