### ISSUE TITLE
How to load urls

### ISSUE THREAD

**Issue by vieruuuu** [GoogleChromeLabs/carlo#45]
Using `app.load(`http://localhost:${port}`)` throws `net::ERR_NAME_NOT_RESOLVED at https://domain/http://localhost:3000`

**Comment by pavelfeldman** [comment]
You should not navigate to the locally serving pages from Carlo. Carlo is hermetic, it makes files that you have in your project available to Chrome without any servers. Please refer to the [serveFolder](https://github.com/GoogleChromeLabs/carlo/blob/master/API.md#appservefolderfolder-prefix) and examples for more details, but in short, you should do:

```js
app.serveFolder(__dirname + '/www');
app.load('index.html');
```

where `www` is a folder in your project and `index.html` is a file in `www`.

**Comment by nklayman** [comment]
However, in development, you may want to load from a webpack dev server (or something similar). What is the best way to go about this?

**Comment by pavelfeldman** [comment]
Added [app.serveOrigin](https://github.com/GoogleChromeLabs/carlo/blob/master/API.md#appserveoriginorigin) for this in https://github.com/GoogleChromeLabs/carlo/commit/e384301633c59061bac6aa6959e4566b4e45c598.
