### ISSUE TITLE
please not use "pack" instructions in npm scripts at example project

### ISSUE THREAD

**Issue by flasco** [GoogleChromeLabs/carlo#54]
actually, when I exec `yarn pack`, it will trigger a "pack"  instructions, pack your project code, rather than `pkg package.json`. I have to say it's a bad experience of developer, I even thought it's a bug of pkg and I search from issues to find a solution at a long time....

By the way, my environment is osx 10.13.6, yarn 1.12.1, node 8.11.3

**Comment by flasco** [comment]
> yarn pack
Creates a compressed gzip archive of package dependencies.
yarn pack --filename <filename>
Creates a compressed gzip archive of package dependencies and names the file filename.

**Comment by flasco** [comment]
https://yarnpkg.com/en/docs/cli/pack

**Comment by flasco** [comment]
I means that `pack` is a protected value in yarn CLI, use it in `package.json scripts` is futile.

**Comment by flasco** [comment]
"pack": "pkg . -t macos",
 "build": "pkg . -t macos",

in `yarn`, use `yarn build` can trigger `pkg . -t macos"` in expected way, but `pack` not.

**Comment by pavelfeldman** [comment]
Fixed in https://github.com/GoogleChromeLabs/carlo/commit/62247bb278737ed1d8dad9f66ab7700c70098aa5
