### ISSUE TITLE
Will this ever be supported on ChromeOS?

### ISSUE THREAD

**Issue by kyleplo** [GoogleChromeLabs/carlo#55]
I want to develop an app that will work on Windows, Mac, Linux and ChromeOS. If ChromeOS is supported, this would be great!

**Comment by pavelfeldman** [comment]
Carlo is a framework for Node that provides is with rendering capabilities. As there is no Node on ChromeOS, it can't run there.

**Comment by coreytrampe** [comment]
So, not gonna work with Crostini?

**Comment by pavelfeldman** [comment]
Hm, good question. Technically, we should be able to make it work with Crostini. All we need is a VM that runs Node there. Might require minor modifications to CrOS to reuse CrOS web content.

**Comment by coreytrampe** [comment]
Maybe another little program could proxy to the native Chrome?

**Comment by jamesopstad** [comment]
I actually presumed that ChromeOS support was one of the motivations for Carlo before seeing this. It seems wasteful that Electron apps running in Crostini are using a separate Chromium build when the whole OS is built around Chrome. If Carlo could bridge the gap between ChromeOS and Node running inside the Crostini VM then that seems like a really promising way to bring more complex apps to ChromeOS.
