### ISSUE TITLE
Way to customize carlo.serveFolder more

### ISSUE THREAD

**Issue by ak239** [GoogleChromeLabs/carlo#60]
Imagine I have following local directories:
/frontend/app.html
/frontend/app.json
/frontend/moduleA
/override/app.json
/override/moduleB

/frontend/ folder is located inside another package and I can not just put my overrides there. Instead I'd like to call `carlo.serveFolders(['/override', '/frontend'])` method, later carlo should lookup file in override folder first and if it does not exist fallback to frontend folder. As a result my app can access following files:
/frontend/app.html
/override/app.json
/frontend/moduleA
/frontend/moduleB

I think it is possible to solve this problem for modules with prefixes but it looks like there is no easy way to make possible per file override, e.g. app.json.

**Comment by pavelfeldman** [comment]
Fixed as https://github.com/GoogleChromeLabs/carlo/commit/2b471afb3a822aed855a4ab1eefdeb500f211c16
