### ISSUE TITLE
Could node app with carlo package to a Desktop app?

### ISSUE THREAD

**Issue by sandangel** [GoogleChromeLabs/carlo#7]
Is it possible to package node app with carlo to a Desktop app? I don't want to use electron because of high memory usage and you have to bundle chromium.

**Comment by pavelfeldman** [comment]
Sure, check out systeminfo example and call `pkg package.json` to bundle it into an executable. It does not give you branding such as Icon and app name in menus, but it would work.

**Comment by pavelfeldman** [comment]
Added to the FAQ.
