### ISSUE TITLE
disable "Hold command-q to quit"

### ISSUE THREAD

**Issue by hinzundcode** [GoogleChromeLabs/carlo#70]
I have to hold command-q to quit Chrome, which is nice if I use Chrome as a browser, but for "native" applications it is kinda weird. Is it possible to override this for Carlo applications?

**Comment by Dacturne** [comment]
What do you mean? If what you meant is closing the whole App with a button click, then just use `rpc` and `process.exit()`
Closing a single instance would be done via [App.exit()](https://github.com/GoogleChromeLabs/carlo/blob/master/API.md#appexit)
```javascript
// index.js
const carlo = require('carlo')
const { rpc } = require('carlo/rpc')
class Backend {
    async exitApp() {
        console.log('Closing app');
        process.exit()
    }
}
(async () => {
    const app = await carlo.launch({
        width: 300,
        height: 300
    })
    app.on('exit', () => process.exit())
    app.serveFolder(__dirname)
    app.load('index.html', rpc.handle(new Backend()))
})()
```
```html
<!-- index.html -->
<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    button {
        width: 10rem;
        height: 3rem;
    }
</style>
<button onclick="clickHandler();return false;">Click to close</button>
<script>
    let _backend
    async function load(backend) {
        _backend = backend
    }
    function clickHandler() {
        _backend.exitApp()
    }
</script>
```

**Comment by hinzundcode** [comment]
![screen shot 2018-11-09 at 16 07 10](https://user-images.githubusercontent.com/651492/48270510-91ca7200-e43a-11e8-974a-b22fb4b8a70b.png)

I configured Chrome so that I have to hold Cmd+Q in order to close it. Is it possible to override this behaviour for Carlo without disabling it in Chrome itself?

**Comment by Dacturne** [comment]
If it's binded in the OS - probably not
If it's binded in chrome itself (user profile), then try using the `kiosk` mode flag or just straight up 
`--incognito`
[list of flags](https://peter.sh/experiments/chromium-command-line-switches/)

**Comment by pavelfeldman** [comment]
This was bugging me as well. I do that in the examples/terminal now, in the user land. I will push that code into Carlo itself.

**Comment by pavelfeldman** [comment]
Fixed as https://github.com/GoogleChromeLabs/carlo/commit/ddffcb7100e106e2416b2c1168bb69d6f4273e09
