### ISSUE TITLE
Add evaluateOnNewDocument method to API

### ISSUE THREAD

**Issue by ak239** [GoogleChromeLabs/carlo#72]
I need some data to be synchronously available in app from its start. E.g., I would like to fetch settings from my own storage and [inject them](https://github.com/GoogleChromeLabs/ndb/blob/master/lib/preferences.js#L25) to the app by evaluating on new document something like:
```
evaluateOnNewDocument(`Settings = { a: 1, b: 2, c: 3}`);
```
I can create file with settings somewhere in temporary directory and then serve it but it looks much less convenient.

**Comment by pavelfeldman** [comment]
You should be able to serve this via network interception now.
