### ISSUE TITLE
How do you test?

### ISSUE THREAD

**Issue by nathfreder** [GoogleChromeLabs/carlo#76]
Hey there,
I am interested in working with `carlo` instead of `electron`, however `electron` comes with a testing framework named `spectron`. Can you provide an example of how to test `carlo`? It would also be great to have an example of debugging in Code.

**Comment by pavelfeldman** [comment]
Carlo uses [Puppeteer](https://pptr.dev/) framework for headless testing. Please refer to the systeminfo [test](https://github.com/GoogleChromeLabs/carlo/blob/master/examples/systeminfo/test.js) as an example.

**Comment by nathfreder** [comment]
Thanks so much!
