### ISSUE TITLE
What happens if a user does not have chrome installed?

### ISSUE THREAD

**Issue by nklayman** [GoogleChromeLabs/carlo#8]
Just wandering what happens if a user tries to run a Carlo app without having chrome installed. Thanks!

**Comment by PikachuHy** [comment]
if no chrome installed
```
  if (!installations.length) {
    throw new Error('The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.');
  }
```
or
```
  const executablePath = findChrome().pop();
  if (!executablePath) {
    console.error('Could not find Chrome installation, please make sure Chrome browser is installed.')
    process.exit(0);
    return;
  }
```

**Comment by pavelfeldman** [comment]
Added your question to the FAQ.

**Comment by arpu** [comment]
would it be possible to bundle the chrome bin with carlo?

**Comment by p01** [comment]
It would be so nice to create two executables: with and without Chrome.
Or even install have Carlo install Chrome when needed.

**Comment by nklayman** [comment]
I agree. It would be even better if Carlo would show a nice error dialog to the user, giving them the option to download chrome.
