### ISSUE TITLE
Canary is downloaded despite it is already installed

### ISSUE THREAD

**Issue by vsemozhetbyt** [GoogleChromeLabs/carlo#87]
I have dev and canary channels installed on my Windows 7 x64 side by side. If I do not use `channel` option in `carlo.launch()`, installed dev is used. If I use `channel: 'canary'`, I get:
```
Downloading Chromium r599821...
Chromium downloaded to C:\Users\[user]\AppData\Roaming\npm\node_modules\carlo\lib\.local-data\win64-599821
```
Is it possible to use already installed canary using `channel` option, without `executablePath` option?

**Comment by pavelfeldman** [comment]
should be `channel: ['canary']`. I'll fix it to support single value though.

**Comment by vsemozhetbyt** [comment]
@pavelfeldman Thank you! I've misread the option type.
Maybe it is worth to correct description for now: https://github.com/GoogleChromeLabs/carlo/pull/91
