### ISSUE TITLE
examples/photobooth saveImage on Windows (quick fix)

### ISSUE THREAD

**Issue by ab35** [GoogleChromeLabs/carlo#89]
On windows operating systems, the method [`toISOString()` ](https://github.com/GoogleChromeLabs/carlo/blob/27db102e58359bb83932863f4097ab880eae9128/examples/photobooth/main.js#L45)does not produce a valid filesystem path:
```js
const fileName = path.join('pictures', new Date().toISOString() + '.jpeg');
```
A quick fix that solves the issue:
```js
const fileName = path.join('pictures', `${new Date().toISOString().replace(/:/g,'-')}.jpeg`);
```

**Comment by pavelfeldman** [comment]
Thanks. https://github.com/GoogleChromeLabs/carlo/commit/ac0271a6ea21d4cefa51605e4bcba375053b7e8c
