### ISSUE TITLE
how to load a url in a new window?

### ISSUE THREAD

**Issue by whatsdis** [GoogleChromeLabs/carlo#97]
hey guys so I need two windows open.

The first is the app window itself. It will be skinny. I need to load an external https:// URL website and show it in a new window beside app window. I want to be able to spawn multiple such externally loaded websites and bring each to a focus when I select it from the app.window

is this possible?

**Comment by pavelfeldman** [comment]
Added [example](https://github.com/GoogleChromeLabs/carlo/tree/master/examples/windows) for you.

**Comment by whatsdis** [comment]
wow....I would not have been able to figure that out on my own
