### ISSUE TITLE
Is it possible to manipulate the mouse and keyboard with carlo?

### ISSUE THREAD

**Issue by whatsdis** [GoogleChromeLabs/carlo#98]
Basically I would like to be able to record a screencast of the operating system, is this possible? is there an api call or example that shows access to OS mouse and keyboard as well as screenshot?

**Comment by pavelfeldman** [comment]
Carlo can manipulate mouse and capture browser screenshots via Puppeteer. But it has no access beyond the browser window unless you implement it natively via Node.
