### ISSUE TITLE
Wrong chrome path priority?

### ISSUE THREAD

**Issue by xyc** [GoogleChromeLabs/carlo#99]
Looks that sorting exec path priorities places path with greater weight in the beginning.
https://github.com/GoogleChromeLabs/carlo/blob/09416d8a49ed6df88fa2f1f62e35c567f072340c/lib/find_chrome.js#L145
But it pops the last (least weight). Is this intentional?
https://github.com/GoogleChromeLabs/carlo/blob/09416d8a49ed6df88fa2f1f62e35c567f072340c/lib/find_chrome.js#L60

**Comment by image72** [comment]
I tested in company almost 5 computers, but never run any example succeed. 
always `Could not find Chrome installation, please make sure Chrome browser is installed from https://www.google.com/chrome/.`

**Comment by xyc** [comment]
Yes, I have multiple Chrome installs. I expect it to pick up `/Applications/Google Chrome.app` but it pick up the lower priority one (which is not the latest version). Reversing the weight comparator would resolve it.

**Comment by pavelfeldman** [comment]
Fixed in https://github.com/GoogleChromeLabs/carlo/commit/e33f9d13da41b13372aa6ba20742f5e240412b39

**Comment by xyc** [comment]
👍 thank you!
